language: cpp

sudo: false

addons:
  apt:
    packages:
      - g++-4.8
      - cmake
      - libboost1.55-all-dev
      - zlib1g-dev
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libavformat-dev
      - libswscale-dev
      - $PACKAGE

before_install:
  #new Clang
  #- sudo add-apt-repository --yes ppa:h-rayflood/llvm
  #new SDL2
  #- sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots
  #new Qt
  #- sudo add-apt-repository --yes ppa:beineri/opt-qt532

    #- sudo apt-get update -qq

    #- sudo apt-get install -qq libsdl2-image-dev libsdl2-mixer-dev
    #- sudo apt-get install -qq qt53declarative

  #setup compiler
  #- source /opt/qt53/bin/qt53-env.sh
  #- export CC=${REAL_CC} CXX=${REAL_CXX}

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

env:
  - ignore=this

matrix:
  exclude:
    - env: ignore=this
  include:
    - compiler: clang # fails all the time - missing packages?
      env: REAL_CC=clang-3.2 REAL_CXX=clang++-3.2 PACKAGE=clang-3.2
    - compiler: clang
      env: REAL_CC=clang-3.3 REAL_CXX=clang++-3.3 PACKAGE=clang-3.3
    - compiler: clang
      env: REAL_CC=clang-3.4 REAL_CXX=clang++-3.4 PACKAGE=clang-3.4
    #- compiler: gcc # fails due to running out of memory - vcmi need too much of it for successfull compilation
    #  env: REAL_CC=gcc-4.7   REAL_CXX=g++-4.7     PACKAGE=g++-4.7   SUPPORT=
    #- compiler: gcc # same as 4.7
    #  env: REAL_CC=gcc-4.8   REAL_CXX=g++-4.8     PACKAGE=g++-4.8   SUPPORT=

    #notifications:
    #  email:
    #    recipients:
        #    - vcmi.fail@mixaill.tk
        #    - saven.ivan@gmail.com
        #    on_success: change
        #    on_failure: always
